language: php

matrix:
    include:
        - php: 5.6
        - php: 7.0
        - php: 7.1
        - php: 7.2
        - php: 7.3
          env: PHP_CS_FIXER_IGNORE_ENV=1 IGNORE_PLATFORM_REQS=--ignore-platform-reqs # awful ugly hack
    fast_finish: true

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - phpenv config-rm xdebug.ini || return 0
  - travis_retry composer self-update

install:
  - travis_retry composer update --no-interaction $IGNORE_PLATFORM_REQS

script:
  - composer validate --strict --no-check-lock
  - composer check-style
  - composer test
