language: php

matrix:
    include:
        - php: 5.6
        - php: 7.0
        - php: 7.1
        - php: 7.2
        - php: 7.3
    fast_finish: true

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - phpenv config-rm xdebug.ini || return 0
  - travis_retry composer self-update

install:
  - travis_retry composer update --no-interaction

script:
  - composer validate --strict --no-check-lock
  - ./vendor/bin/php-cs-fixer fix . -v --dry-run --using-cache=no
  - ./vendor/bin/phpunit
